export const GET_BREEDS = "GET_BREEDS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_BREEDS_BY_NAME = "GET_BREEDS_BY_NAME";
export const GET_DETAILS = "GET_DETAILS";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_GROUPS = "GET_GROUPS";

export const POST_BREED = "CREATE_BREED";

export const FILTER_BY_BREED = "FILTER_BY_BREED";
export const FILTER_CREATED_DB = "FILTER_CREATED_DB";
export const FILTER_BY_GROUPS = "FILTER_BY_GROUPS";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";

export const ORDER_BY_BREED = "ORDER_BY_BREED";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";

export const CLEAR_DETAIL = "CLEAR_DETAIL";
